In [2]:
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('../artifacts/data_ingestion/dataset.csv')

In [4]:
df.shape

(10692, 13)

In [3]:
data = df
        
data = data.drop_duplicates()

cols = ['Homeowners Association', 'property_tax','fire_insurance', 'total_amount']
data = data.drop(columns = cols)



X = data.drop(columns=['rent_amount'])
y = data['rent_amount']
X_train, X_test, y_train, y_test = train_test_split(
    X, y , test_size = 0.2, random_state=42
)

In [5]:
X

City  area  rooms  bathrooms  parking Space  floor  \
0           Sao Paulo    70      2          1              1      7   
1           Sao Paulo   320      4          4              0     20   
2        Porto Alegre    80      1          1              1      6   
3        Porto Alegre    51      2          1              0      2   
4           Sao Paulo    25      1          1              0      1   
...               ...   ...    ...        ...            ...    ...   
10687    Porto Alegre    63      2          1              1      5   
10688       Sao Paulo   285      4          4              4     17   
10689  Rio de Janeiro    70      3          3              0      8   
10690  Rio de Janeiro   120      2          2              2      8   
10691       Sao Paulo    80      2          1              0      0   

            pets      furnished  
0          acept      furnished  
1          acept  not furnished  
2          acept  not furnished  
3          acept  not furnished  
4      not acept  not furnished  
...          ...            ...  
10687  not acept      furnished  
10688      acept  not furnished  
10689  not acept      furnished  
10690      acept      furnished  
10691      acept  not furnished  

[10334 rows x 8 columns]

In [14]:
df['City'].unique()

array(['Sao Paulo', 'Porto Alegre', 'Rio de Janeiro', 'Campinas',
       'Belo Horizonte'], dtype=object)

In [6]:
y

0         3300
1         4960
2         2800
3         1112
4          800
         ...  
10687     1478
10688    15000
10689     6000
10690    12000
10691     1400
Name: rent_amount, Length: 10334, dtype: int64

In [7]:
X_train.shape

(8267, 8)

In [8]:
X_test.shape

(2067, 8)

In [9]:
def remove_outliers_iqr(train_df, test_df, cols):
    train_df = train_df.copy()
    test_df = test_df.copy()
    for col in cols:
        q1 = train_df[col].quantile(0.25)
        q3 = train_df[col].quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        train_df = train_df[(train_df[col] >= lower) & (train_df[col] <= upper)]
        test_df = test_df[(test_df[col] >= lower) & (test_df[col] <= upper)]
    return train_df, test_df

In [10]:
X_train, X_test = remove_outliers_iqr(X_train, X_test, ['area','floor'])


In [11]:
X_train.shape

(7594, 8)

In [12]:
X_test.shape

(1911, 8)

In [13]:
y_train = y_train.loc[X_train.index]
y_train

4966     1000
6806     7800
6598     6000
4225     3900
829      2200
        ...  
5859     3000
5291    11500
5497      790
861      3148
7452     7935
Name: rent_amount, Length: 7594, dtype: int64

In [15]:
X_train = joblib.load(r'C:\house-rent-prediction-model\artifacts\data_transformation\X_train.joblib')
y_train = joblib.load(r'C:\house-rent-prediction-model\artifacts\data_transformation\y_train.joblib')
X_test = joblib.load(r'C:\house-rent-prediction-model\artifacts\data_transformation\X_test.joblib')
y_test = joblib.load(r'C:\house-rent-prediction-model\artifacts\data_transformation\y_test.joblib')
X_test_dataframe = pd.read_csv(r'C:\house-rent-prediction-model\artifacts\data_transformation\ref.csv')



In [16]:
X_test[0]

array([ 1.12786777,  2.4017957 , -0.07307762,  0.37882104, -1.0510039 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ])

In [17]:
y_test[0]

3300

In [18]:
poly_fea = joblib.load(r'C:\house-rent-prediction-model\artifacts\model_training\polynomial_feat_extr.joblib')
poly = joblib.load(r'C:\house-rent-prediction-model\artifacts\model_training\poly_reg.joblib')
random = joblib.load(r'C:\house-rent-prediction-model\artifacts\model_training\random_forest.joblib')
xg = joblib.load(r'C:\house-rent-prediction-model\artifacts\model_training\xgboost.joblib')
mlp = joblib.load(r'C:\house-rent-prediction-model\artifacts\model_training\mlp.joblib')


In [19]:
random.predict(X_test[0].reshape(1,11))

array([3673.17])

In [20]:
X_test_dataframe.iloc[0]

City             Belo Horizonte
area                        216
rooms                         5
bathrooms                     2
parking Space                 2
floor                         0
pets                      acept
furnished         not furnished
Name: 0, dtype: object

In [21]:
mlp.predict(X_test[0].reshape(1,11))

array([4581.89058485])